// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs edit-markdown-table`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "markdown-viewer",
    "icon": "📄",
    "name": {
      "en": "Markdown Viewer",
      "ja": "Markdownビューアー",
      "zh": "Markdown 查看器",
      "de": "Markdown-Betrachter",
      "es": "Visor de Markdown"
    },
    "desc": {
      "en": "Open a local .md file and read it as sanitized, rendered HTML.",
      "ja": "ローカルの.mdファイルを、サニタイズ済みのHTMLとして表示。",
      "zh": "打开本地 .md 文件，以净化后的 HTML 渲染显示。",
      "de": "Öffne eine lokale .md-Datei und lies sie als bereinigtes, gerendertes HTML.",
      "es": "Abre un archivo .md local y léelo como HTML renderizado y depurado."
    }
  },
  {
    "slug": "xlsx-to-markdown",
    "icon": "📝",
    "name": {
      "en": "XLSX to Markdown Table",
      "ja": "XLSX→Markdown変換",
      "zh": "XLSX 转 Markdown 表格",
      "de": "XLSX zu Markdown-Tabelle",
      "es": "XLSX a tabla Markdown"
    },
    "desc": {
      "en": "Turn a worksheet into a Markdown table you can copy or download.",
      "ja": "シートをMarkdownテーブルに変換、コピーまたはダウンロード。",
      "zh": "将工作表转换为 Markdown 表格，可复制或下载。",
      "de": "Wandelt ein Arbeitsblatt in eine Markdown-Tabelle zum Kopieren oder Herunterladen um.",
      "es": "Convierte una hoja en una tabla Markdown para copiar o descargar."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'edit-markdown-table';
